[[redirects]]
  from = "/api"
  to = "https://yalla-neftar.azurewebsites.net/"
  status = 200
  force = true


[[redirects]]
  from = "/jsonplaceholder"
  to = "https://jsonplaceholder.typicode.com/"
  status = 200
  force = true
