[[redirects]]
  from = "/api"
  to = "https://yalla-neftar.azurewebsites.net/"
  host = "yalla-neftar.azurewebsites.net"
  status = 200
  force = true


[[redirects]]
  from = "/jsonplaceholder"
  to = "https://jsonplaceholder.typicode.com/"
  host = "jsonplaceholder.typicode"
  status = 200
  force = true
